<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCmoxmcw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCmoxmcw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCmoxmcw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCmoxmcw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCmoxmcw\appProdProjectContainer([
    'container.build_hash' => 'Cmoxmcw',
    'container.build_id' => '10dda508',
    'container.build_time' => 1642430819,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCmoxmcw');
